name: Deploy on remote server
on:
  push:
    branches:
      - master
jobs:
  deploy-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: "/home/music-bot/install-and-start"
