name: Deploy on remote server
on:
  push:
    branches:
      - feat/ci
jobs:
  deploy-and-run:
    runs-on: ubuntu-latest
    steps:
      - run: 'ls'
      - uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/music-bot"
      - run: 'echo "Finish deploy"'
          
